name: Dynamic runner example
on: [push]
jobs:
  choose-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.choice.outputs.RUNNER }}
    steps:
      - uses: actions/checkout@v3
      - id: choice
        run: echo "RUNNER=$(python3 example.py runner)" >> "$GITHUB_OUTPUT"

  use-runner:
    needs: [choose-runner]
    runs-on: ${{ needs.choose-runner.outputs.runner }}
    steps:
      - uses: actions/checkout@v3
      - id: info
        run: python3 example.py info